"""Language and script metadata for rendering pipelines."""

LANGUAGE_CODES = {
    "Afrikaans": "af",
    "Albanian": "sq",
    "Arabic": "ar",
    "Amharic": "am",
    "Armenian": "hy",
    "Basque": "eu",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bulgarian": "bg",
    "Bosnian": "bs",
    "Burmese": "my",
    "Catalan": "ca",
    "Kazakh": "kk",
    "Kyrgyz": "ky",
    "Mongolian": "mn",
    "Tajik": "tg",
    "Turkmen": "tk",
    "Uzbek": "uz",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Czech": "cs",
    "Croatian": "hr",
    "Danish": "da",
    "Dutch": "nl",
    "English": "en",
    "Esperanto": "eo",
    "Estonian": "et",
    "Faroese": "fo",
    "Filipino": "tl",
    "Finnish": "fi",
    "French": "fr",
    "German": "de",
    "Georgian": "ka",
    "Greek": "el",
    "Gujarati": "gu",
    "Hausa": "ha",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Irish": "ga",
    "Icelandic": "is",
    "Indonesian": "id",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jw",
    "Kannada": "kn",
    "Khmer": "km",
    "Korean": "ko",
    "Latin": "la",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Luxembourgish": "lb",
    "Macedonian": "mk",
    "Malay": "ms",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Marathi": "mr",
    "Nepali": "ne",
    "Norwegian": "no",
    "Pashto": "ps",
    "Polish": "pl",
    "Portuguese": "pt",
    "Punjabi": "pa",
    "Scots": "sco",
    "Scottish Gaelic": "gd",
    "Galician": "gl",
    "Romani": "rom",
    "Spanish": "es",
    "Romanian": "ro",
    "Russian": "ru",
    "Sinhala": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Serbian": "sr",
    "Sundanese": "su",
    "Swahili": "sw",
    "Swedish": "sv",
    "Tamil": "ta",
    "Telugu": "te",
    "Thai": "th",
    "Turkish": "tr",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Vietnamese": "vi",
    "Welsh": "cy",
    "Xhosa": "xh",
    "Yoruba": "yo",
    "Zulu": "zu",
    "Persian": "fa",
}

NON_LATIN_LANGUAGES = {
    "Arabic",
    "Armenian",
    "Bulgarian",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Hebrew",
    "Japanese",
    "Korean",
    "Russian",
    "Thai",
    "Greek",
    "Hindi",
    "Bengali",
    "Tamil",
    "Telugu",
    "Gujarati",
    "Persian",
    "Burmese",
    "Myanmar",
    "Khmer",
    "Nepali",
    "Marathi",
    "Kannada",
    "Malayalam",
    "Sinhala",
    "Urdu",
    "Ukrainian",
    "Georgian",
    "Amharic",
    "Pashto",
    "Punjabi",
    "Kazakh",
    "Kyrgyz",
    "Mongolian",
    "Tajik",
}
