import SwiftUI

extension AppleBookCreateView {
    var sourceSection: some View {
        AppleBookCreateSourceSection(
            creationMode: $creationMode,
            availableCreateModes: availableCreateModes,
            showsJobTypePicker: false,
            showsNarrateRangeControls: false,
            sourcePath: narrateSourcePathBinding,
            sourceStartSentence: textBinding(for: .sourceStartSentence, value: $sourceStartSentence),
            sourceEndSentence: textBinding(for: .sourceEndSentence, value: $sourceEndSentence),
            narrateSourcePanel: $narrateSourcePanel,
            subtitleSourcePath: textBinding(for: .subtitleSourcePath, value: $subtitleSourcePath),
            youtubeBaseDir: $youtubeBaseDir,
            youtubeVideoPath: textBinding(for: .youtubeVideoPath, value: $youtubeVideoPath),
            youtubeSubtitlePath: textBinding(for: .youtubeSubtitlePath, value: $youtubeSubtitlePath),
            youtubeSubtitleExtractionLanguages: $youtubeSubtitleExtractionLanguages,
            pipelineFiles: viewModel.pipelineFiles,
            acquisitionProviders: viewModel.acquisitionProviders,
            acquisitionDefaultProviderIds: viewModel.acquisitionDefaultProviderIds,
            ebookAcquisitionDiscovery: viewModel.ebookAcquisitionDiscovery,
            youtubeAcquisitionDiscovery: viewModel.youtubeAcquisitionDiscovery,
            downloadStationJob: viewModel.downloadStationJob,
            subtitleSources: viewModel.subtitleSources,
            youtubeLibrary: viewModel.youtubeLibrary,
            youtubeInlineSubtitleStreams: viewModel.youtubeInlineSubtitleStreams,
            selectedNarrateFileName: selectedNarrateFileName,
            selectedSubtitleFileName: selectedSubtitleFileName,
            narrateChapterOptions: viewModel.narrateChapterOptions,
            selectedNarrateStartChapterID: $selectedNarrateStartChapterID,
            selectedNarrateEndChapterID: $selectedNarrateEndChapterID,
            isLoadingPipelineFiles: viewModel.isLoadingPipelineFiles,
            isUploadingPipelineEbook: viewModel.isUploadingPipelineEbook,
            isLoadingEbookAcquisitionDiscovery: viewModel.isLoadingEbookAcquisitionDiscovery,
            isAcquiringEbookAcquisitionCandidate: viewModel.isAcquiringEbookDiscoveryCandidate,
            isLoadingYoutubeAcquisitionDiscovery: viewModel.isLoadingYoutubeAcquisitionDiscovery,
            isPreparingYoutubeAcquisitionCandidate: viewModel.isPreparingYoutubeAcquisitionCandidate,
            isLoadingNarrateChapters: viewModel.isLoadingNarrateChapters,
            isSubmittingDownloadStation: viewModel.isSubmittingDownloadStation,
            isPollingDownloadStation: viewModel.isPollingDownloadStation,
            isDeletingPipelineEbook: viewModel.isDeletingPipelineEbook,
            isLoadingSubtitleSources: viewModel.isLoadingSubtitleSources,
            isDeletingSubtitleSource: viewModel.isDeletingSubtitleSource,
            isLoadingYoutubeLibrary: viewModel.isLoadingYoutubeLibrary,
            isLoadingYoutubeSubtitleStreams: viewModel.isLoadingYoutubeSubtitleStreams,
            isExtractingYoutubeSubtitles: viewModel.isExtractingYoutubeSubtitles,
            pipelineFilesErrorMessage: viewModel.pipelineFilesErrorMessage,
            narrateChaptersErrorMessage: viewModel.narrateChaptersErrorMessage,
            subtitleSourcesErrorMessage: viewModel.subtitleSourcesErrorMessage,
            youtubeLibraryErrorMessage: viewModel.youtubeLibraryErrorMessage,
            ebookAcquisitionDiscoveryErrorMessage: viewModel.ebookAcquisitionDiscoveryErrorMessage,
            youtubeAcquisitionDiscoveryErrorMessage: viewModel.youtubeAcquisitionDiscoveryErrorMessage,
            downloadStationMessage: viewModel.downloadStationMessage,
            downloadStationErrorMessage: viewModel.downloadStationErrorMessage,
            acquisitionProvidersErrorMessage: viewModel.acquisitionProvidersErrorMessage,
            youtubeSearchUnavailableMessage: videoDiscoveryAvailability.youtubeSearchUnavailableMessage,
            isYoutubeSearchAvailable: videoDiscoveryAvailability.isYoutubeSearchAvailable,
            downloadStationUnavailableMessage: videoDiscoveryAvailability.downloadStationUnavailableMessage,
            isDownloadStationAvailable: videoDiscoveryAvailability.isDownloadStationAvailable,
            youtubeSubtitleExtractionMessage: viewModel.youtubeSubtitleExtractionMessage,
            youtubeSubtitleExtractionErrorMessage: viewModel.youtubeSubtitleExtractionErrorMessage,
            onRefreshPipelineFiles: refreshPipelineFilesFromSourceSection,
            onSearchAcquisitionDiscovery: searchAcquisitionDiscovery,
            onSelectAcquisitionCandidate: applyAcquisitionDiscoveryCandidate,
            onDeletePipelineEbook: requestDeletePipelineEbook,
            onRefreshSubtitleSources: refreshSubtitleSourcesFromSourceSection,
            onDeleteSubtitleSource: requestDeleteSubtitleSource,
            onRefreshYoutubeLibrary: refreshYoutubeLibraryFromSourceSection,
            onSearchYoutubeAcquisitionDiscovery: searchYoutubeAcquisitionDiscovery,
            onSelectYoutubeAcquisitionCandidate: applyYoutubeAcquisitionDiscoveryCandidate,
            onSubmitDownloadStation: submitDownloadStation,
            onPollDownloadStation: pollDownloadStation,
            onInspectYoutubeSubtitles: inspectYoutubeSubtitles,
            onExtractYoutubeSubtitles: extractYoutubeSubtitles,
            onLoadNarrateChapters: loadNarrateChapters,
            onChooseNarrateFile: chooseNarrateFile,
            onChooseSubtitleFile: chooseSubtitleFile
        )
    }
}
