"""Pydantic schemas for the FastAPI web backend."""

from __future__ import annotations

from .audio import GTTSLanguage, MacOSVoice, VoiceInventoryResponse, VoiceMatchResponse
from .access import AccessGrantPayload, AccessPolicyPayload, AccessPolicyUpdateRequest
from .auth import (
    LoginRequestPayload,
    OAuthLoginRequestPayload,
    PasswordChangeRequestPayload,
    RegistrationRequestPayload,
    RegistrationResponse,
    SessionStatusResponse,
    SessionUserPayload,
)
from .assistant import (
    AssistantChatMessage,
    AssistantLookupRequest,
    AssistantLookupResponse,
    AssistantRequestContext,
    LLMModelListResponse,
)
from .audio_synthesis import AudioSynthesisError, AudioSynthesisRequest
from .library import (
    LibraryIsbnLookupResponse,
    LibraryIsbnUpdateRequest,
    LibraryItemPayload,
    LibraryMediaRemovalResponse,
    LibraryMetadataEnrichRequest,
    LibraryMetadataEnrichResponse,
    LibraryMetadataRefreshRequest,
    LibraryMetadataRefreshResponse,
    LibraryMetadataUpdateRequest,
    LibraryMoveRequest,
    LibraryMoveResponse,
    LibraryReindexResponse,
    LibrarySearchResponse,
)
from .metadata_lookup import (
    BookOpenLibraryMetadataLookupRequest,
    BookOpenLibraryMetadataPreviewLookupRequest,
    BookOpenLibraryMetadataPreviewResponse,
    BookOpenLibraryMetadataResponse,
    BookOpenLibraryQuery,
    YoutubeVideoMetadataLookupRequest,
    YoutubeVideoMetadataParse,
    YoutubeVideoMetadataPreviewLookupRequest,
    YoutubeVideoMetadataPreviewResponse,
    YoutubeVideoMetadataResponse,
)
from .pipeline_files import PipelineFileBrowserResponse, PipelineFileEntry
from .pipeline_jobs import (
    ImageGenerationSummary,
    JobParameterSnapshot,
    PipelineJobActionResponse,
    PipelineJobListResponse,
    PipelineStatusResponse,
)
from .pipeline_media import (
    AudioTrackMetadata,
    ChunkSentenceImagePayload,
    ChunkSentenceMetadata,
    ChunkSentenceTimelineEvent,
    ChunkSentenceVariant,
    MediaSearchHit,
    MediaSearchResponse,
    PipelineMediaChunk,
    PipelineMediaFile,
    PipelineMediaResponse,
)
from .pipeline_requests import (
    BookContentIndexResponse,
    ImageNodeAvailabilityEntry,
    ImageNodeAvailabilityRequest,
    ImageNodeAvailabilityResponse,
    PipelineDefaultsResponse,
    PipelineFileDeleteRequest,
    PipelineInputPayload,
    PipelineRequestPayload,
    PipelineSubmissionResponse,
)
from .pipeline_results import PipelineResponsePayload
from .progress import ProgressEventPayload, ProgressSnapshotPayload
from .subtitles import (
    SubtitleDeleteRequest,
    SubtitleDeleteResponse,
    SubtitleSourceEntry,
    SubtitleSourceListResponse,
    SubtitleSubmissionPayload,
    SubtitleTvMetadataLookupRequest,
    SubtitleTvMetadataParse,
    SubtitleTvMetadataPreviewLookupRequest,
    SubtitleTvMetadataPreviewResponse,
    SubtitleTvMetadataResponse,
)
from .users import (
    ManagedUserPayload,
    UserAccountResponse,
    UserCreateRequestPayload,
    UserListResponse,
    UserPasswordResetRequestPayload,
    UserUpdateRequestPayload,
)
from .youtube import (
    YoutubeDubRequest,
    YoutubeDubResponse,
    YoutubeInlineSubtitleListResponse,
    YoutubeInlineSubtitleStream,
    YoutubeNasLibraryResponse,
    YoutubeNasSubtitlePayload,
    YoutubeNasVideoPayload,
    YoutubeSubtitleDeleteRequest,
    YoutubeSubtitleDeleteResponse,
    YoutubeSubtitleDownloadRequest,
    YoutubeSubtitleDownloadResponse,
    YoutubeSubtitleExtractionRequest,
    YoutubeSubtitleExtractionResponse,
    YoutubeSubtitleListResponse,
    YoutubeSubtitleTrackPayload,
    YoutubeVideoDeleteRequest,
    YoutubeVideoDeleteResponse,
    YoutubeVideoDownloadRequest,
    YoutubeVideoDownloadResponse,
    YoutubeVideoFormatPayload,
)
from .media import (
    AudioGenerationParameters,
    MediaAPISettings,
    MediaErrorResponse,
    MediaGenerationRequestPayload,
    MediaGenerationResponse,
    VideoGenerationParameters,
)
from .video import VideoGenerationRequest, VideoGenerationResponse
from .video_jobs import VideoJobResultPayload, VideoJobStatusResponse, VideoJobSubmissionResponse

__all__ = [
    "AudioGenerationParameters",
    "AccessGrantPayload",
    "AccessPolicyPayload",
    "AccessPolicyUpdateRequest",
    "AudioSynthesisError",
    "AudioSynthesisRequest",
    "AudioTrackMetadata",
    "AssistantChatMessage",
    "AssistantLookupRequest",
    "AssistantLookupResponse",
    "AssistantRequestContext",
    "BookContentIndexResponse",
    "BookOpenLibraryMetadataLookupRequest",
    "BookOpenLibraryMetadataPreviewLookupRequest",
    "BookOpenLibraryMetadataPreviewResponse",
    "BookOpenLibraryMetadataResponse",
    "BookOpenLibraryQuery",
    "ChunkSentenceImagePayload",
    "ChunkSentenceMetadata",
    "ChunkSentenceTimelineEvent",
    "ChunkSentenceVariant",
    "GTTSLanguage",
    "ImageGenerationSummary",
    "ImageNodeAvailabilityEntry",
    "ImageNodeAvailabilityRequest",
    "ImageNodeAvailabilityResponse",
    "JobParameterSnapshot",
    "LibraryIsbnLookupResponse",
    "LibraryIsbnUpdateRequest",
    "LibraryItemPayload",
    "LibraryMediaRemovalResponse",
    "LibraryMetadataEnrichRequest",
    "LibraryMetadataEnrichResponse",
    "LibraryMetadataRefreshRequest",
    "LibraryMetadataRefreshResponse",
    "LibraryMetadataUpdateRequest",
    "LibraryMoveRequest",
    "LibraryMoveResponse",
    "LibraryReindexResponse",
    "LibrarySearchResponse",
    "LLMModelListResponse",
    "LoginRequestPayload",
    "OAuthLoginRequestPayload",
    "MacOSVoice",
    "ManagedUserPayload",
    "MediaAPISettings",
    "MediaErrorResponse",
    "MediaGenerationRequestPayload",
    "MediaGenerationResponse",
    "MediaSearchHit",
    "MediaSearchResponse",
    "PasswordChangeRequestPayload",
    "PipelineDefaultsResponse",
    "PipelineFileBrowserResponse",
    "PipelineFileDeleteRequest",
    "PipelineFileEntry",
    "PipelineInputPayload",
    "PipelineJobActionResponse",
    "PipelineJobListResponse",
    "PipelineMediaChunk",
    "PipelineMediaFile",
    "PipelineMediaResponse",
    "PipelineRequestPayload",
    "PipelineResponsePayload",
    "PipelineStatusResponse",
    "PipelineSubmissionResponse",
    "ProgressEventPayload",
    "ProgressSnapshotPayload",
    "RegistrationRequestPayload",
    "RegistrationResponse",
    "SessionStatusResponse",
    "SessionUserPayload",
    "SubtitleDeleteRequest",
    "SubtitleDeleteResponse",
    "SubtitleSourceEntry",
    "SubtitleSourceListResponse",
    "SubtitleSubmissionPayload",
    "SubtitleTvMetadataLookupRequest",
    "SubtitleTvMetadataParse",
    "SubtitleTvMetadataPreviewLookupRequest",
    "SubtitleTvMetadataPreviewResponse",
    "SubtitleTvMetadataResponse",
    "UserAccountResponse",
    "UserCreateRequestPayload",
    "UserListResponse",
    "UserPasswordResetRequestPayload",
    "UserUpdateRequestPayload",
    "VideoGenerationParameters",
    "VideoGenerationRequest",
    "VideoGenerationResponse",
    "VideoJobResultPayload",
    "VideoJobStatusResponse",
    "VideoJobSubmissionResponse",
    "VoiceInventoryResponse",
    "VoiceMatchResponse",
    "YoutubeDubRequest",
    "YoutubeDubResponse",
    "YoutubeInlineSubtitleListResponse",
    "YoutubeInlineSubtitleStream",
    "YoutubeNasLibraryResponse",
    "YoutubeNasSubtitlePayload",
    "YoutubeNasVideoPayload",
    "YoutubeSubtitleDeleteRequest",
    "YoutubeSubtitleDeleteResponse",
    "YoutubeSubtitleDownloadRequest",
    "YoutubeSubtitleDownloadResponse",
    "YoutubeSubtitleExtractionRequest",
    "YoutubeSubtitleExtractionResponse",
    "YoutubeSubtitleListResponse",
    "YoutubeSubtitleTrackPayload",
    "YoutubeVideoDeleteRequest",
    "YoutubeVideoDeleteResponse",
    "YoutubeVideoDownloadRequest",
    "YoutubeVideoDownloadResponse",
    "YoutubeVideoFormatPayload",
    "YoutubeVideoMetadataLookupRequest",
    "YoutubeVideoMetadataParse",
    "YoutubeVideoMetadataPreviewLookupRequest",
    "YoutubeVideoMetadataPreviewResponse",
    "YoutubeVideoMetadataResponse",
]
